name: Auto Grab
on:
  schedule:
    - cron: '*/20 * * * *'
  workflow_dispatch:
jobs:
  update-gist:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: pip install requests
      - name: Run Script
        run: python get_link.py
      - name: Update Gist
        env:
          GIST_ID: ${{ secrets.GIST_ID }}
          GIST_TOKEN: ${{ secrets.GIST_TOKEN }}
        run: |
          # Dùng lệnh curl để đẩy nội dung file list.m3u lên Gist
          CONTENT=$(cat list.m3u | jq -sRr @json)
          curl -X PATCH -H "Authorization: token $GIST_TOKEN" \
               -H "Content-Type: application/json" \
               -d "{\"files\": {\"list.m3u\": {\"content\": $CONTENT}}}" \
               "https://api.github.com/gists/$GIST_ID"
