name: Update M3U 23m
on:
  schedule:
    - cron: '*/23 * * * *' # Chạy tự động mỗi 23 phút
  workflow_dispatch:      # Nút bấm tay cho Mạnh khi MU đá

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install requests

      - name: Run grabber
        run: python grab.py

      - name: Commit and Push
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add live.m3u
          git commit -m "Update playlist - 23m cycle" || exit 0
          git push
